[package]
name = "PEKS"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paired = "0.22.0"
groupy = "0.4.1"
sha2 = "0.10.6"
thiserror = "1.0.37"
fff = "0.3.1"
rand_core = "0.5.1"

[dev-dependencies]
rand_xorshift = "0.2"
rand = "0.8.5"